version: 2

run:
  timeout: 10m
  tests: true

linters:
  enable:
    - gocyclo        # Cyclomatic complexity
    - maintidx       # Maintainability index
    - staticcheck    # Static analysis (comprehensive)
    - unused         # Unused variables, functions, types

linters-settings:
  gocyclo:
    min-complexity: 15  # Warn on functions with >15 cyclomatic complexity

  maintidx:
    under: 100  # Fail if maintainability index drops below 100

issues:
  # In test files, error checks are less critical (best-effort cleanup)
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

  exclude:
    - "should have a package comment"
