version: 2

run:
  timeout: 10m
  tests: true

linters:
  default: none
  enable:
    - ineffassign    # Ineffectual assignments
    - staticcheck    # Static analysis (comprehensive)
    - unused         # Unused variables, functions, types
    - errcheck       # Unchecked error returns (json.Encode, io.Close, etc.)
    - govet          # Go vet with shadow detection
    - copyloopvar    # Loop variable capture bugs (Go 1.22+)

  settings:
    errcheck:
      # Don't require checking these (too noisy, best-effort operations)
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprintln
        - (net/http.ResponseWriter).Write
      # But DO check json.NewEncoder().Encode() and similar

    staticcheck:
      checks:
        - all
        - "-ST1003"   # Allow Go naming convention violations (TabId, sinceTs, etc. — changing breaks JSON API)
        - "-ST1005"   # Allow capitalized error strings (we use structured error messages)

  exclusions:
    rules:
      # Don't enforce errcheck on test files (too noisy)
      - path: _test\.go
        linters:
          - errcheck
    presets:
      - comments
