#!/usr/bin/env python3
"""
Auto-generate FEATURE-NAVIGATION.md from actual folder structure.
Run this after adding/removing features to keep navigation up-to-date.
"""

import os
import sys
from pathlib import Path
from datetime import datetime
import re

DOCS_DIR = Path("/Users/brenn/dev/gasoline")
FEATURES_DIR = DOCS_DIR / "docs/features/feature"
OUTPUT_FILE = DOCS_DIR / "docs/features/FEATURE-NAVIGATION.md"
CURRENT_DATE = datetime.now().strftime("%Y-%m-%d")


def detect_status(feature_dir):
    """Detect feature status from PRODUCT_SPEC.md or TECH_SPEC.md"""
    for spec_file in ["PRODUCT_SPEC.md", "TECH_SPEC.md"]:
        spec_path = feature_dir / spec_file
        if spec_path.exists():
            try:
                with open(spec_path, 'r') as f:
                    content = f.read(500)
                    if "status: shipped" in content:
                        return "shipped"
                    elif "status: in-progress" in content:
                        return "in-progress"
            except:
                pass
    return "proposed"


def get_feature_purpose(feature_dir):
    """Extract feature purpose from PRODUCT_SPEC.md or FEATURE_PROPOSAL.md"""
    for spec_file in ["PRODUCT_SPEC.md", "FEATURE_PROPOSAL.md"]:
        spec_path = feature_dir / spec_file
        if spec_path.exists():
            try:
                with open(spec_path, 'r') as f:
                    for line in f:
                        if line.startswith("# "):
                            return line.replace("# ", "").strip()[:60]
            except:
                pass
    return "(See folder for details)"


def list_feature_files(feature_dir):
    """List all markdown files in feature folder"""
    files = []
    for f in sorted(feature_dir.glob("*.md")):
        if not f.name.startswith("."):
            files.append(f.name)
    return ", ".join(files) if files else ""


def main():
    print("🔄 Generating FEATURE-NAVIGATION.md from folder structure...")
    print(f"📁 Source: {FEATURES_DIR}")
    print(f"📝 Output: {OUTPUT_FILE}")

    # Group features by status
    shipped = []
    in_progress = []
    proposed = []

    # Scan all feature directories
    for feature_dir in sorted(FEATURES_DIR.glob("*")):
        if not feature_dir.is_dir() or feature_dir.name.startswith("."):
            continue

        feature_name = feature_dir.name
        status = detect_status(feature_dir)
        purpose = get_feature_purpose(feature_dir)
        files = list_feature_files(feature_dir)

        entry = {
            'name': feature_name,
            'files': files,
            'purpose': purpose
        }

        if status == "shipped":
            shipped.append(entry)
        elif status == "in-progress":
            in_progress.append(entry)
        else:
            proposed.append(entry)

    # Build the navigation document
    content = f"""---
status: active
scope: feature/navigation
ai-priority: high
tags: [features, navigation, index, lookup, auto-generated]
relates-to: [FEATURE-INDEX.md, README.md]
canonical: true
auto-generated: true
generation-script: scripts/generate-feature-navigation.py
last-verified: {CURRENT_DATE}
---

# Feature Navigation Index

**For LLM Agents:** Quick lookup to find feature documentation folders and their key files.

**Generated:** {CURRENT_DATE} | **Auto-generated by:** `scripts/generate-feature-navigation.py`

---

## Quick Lookup: Find a Feature's Docs

### Format

Each entry shows:
- **Feature name** — Unique identifier for the feature
- **Folder path** — Where docs live (`docs/features/feature/<name>/`)
- **Status** — shipped | in-progress | proposed | deprecated
- **Key files** — What's available in this folder

### Shipped Features (Production)

| Feature | Folder | Files | Purpose |
|---------|--------|-------|---------|
"""

    for entry in shipped:
        content += f"| {entry['name']} | `feature/{entry['name']}/` | {entry['files']} | {entry['purpose']} |\n"

    content += f"""
### In-Progress Features

| Feature | Folder | Files | Purpose |
|---------|--------|-------|---------|
"""

    for entry in in_progress:
        content += f"| {entry['name']} | `feature/{entry['name']}/` | {entry['files']} | {entry['purpose']} |\n"

    content += f"""
### Proposed Features

| Feature | Folder | Files | Purpose |
|---------|--------|-------|---------|
"""

    for entry in proposed:
        content += f"| {entry['name']} | `feature/{entry['name']}/` | {entry['files']} | {entry['purpose']} |\n"

    content += """
---

## Navigation by Use Case

### I need to understand what a feature does
→ Read the feature folder's **PRODUCT_SPEC.md**

### I need to implement a feature
→ Read in order: PRODUCT_SPEC.md → TECH_SPEC.md → QA_PLAN.md

### I need to test a feature
→ Read **QA_PLAN.md** for test scenarios, then check if feature-review.md exists for known issues

### I need to find the codebase implementation
→ Read TECH_SPEC.md and look for "**Code References**" section or `filename:line_number` format

### I need to understand design decisions
→ Read the feature-review.md or check `docs/adrs/ADR-<feature-name>.md`

---

## Folder Structure Template

Each feature folder should contain:

```
feature/<feature-name>/
├── PRODUCT_SPEC.md         # Requirements & user stories
├── TECH_SPEC.md            # Implementation details
├── QA_PLAN.md              # Test scenarios & acceptance criteria
├── <feature>-review.md     # Optional: Principal engineer review
└── [Optional files]
    ├── ADR-<feature>.md    # Links here (actually in /docs/adrs/)
    ├── IMPLEMENTATION_PLAN.md
    ├── MIGRATION.md
    └── [Other docs]
```

---

## How to Add a New Feature

1. Create folder: `docs/features/feature/<feature-name>/`
2. Add PRODUCT_SPEC.md (copy template from `docs/templates/FEATURE-TEMPLATE.md`)
3. Add TECH_SPEC.md
4. Add QA_PLAN.md
5. Create ADR at `docs/adrs/ADR-<feature-name>.md`
6. Update **FEATURE-INDEX.md** with new entry
7. Verify YAML frontmatter on all files
8. Get spec review before implementation
9. **Run this script:** `python3 scripts/generate-feature-navigation.py`

---

## Regenerating This Index

To update this navigation after adding/removing features:

```bash
python3 scripts/generate-feature-navigation.py
```

This script automatically:
- Scans `/docs/features/feature/` for all folders
- Detects feature status from PRODUCT_SPEC.md or TECH_SPEC.md
- Extracts file lists from each folder
- Groups features by status
- Generates consistent documentation

---

## Related Documents

- **FEATURE-INDEX.md** — Status table of all features
- **README.md** — Comprehensive features guide for LLMs
- `docs/core/RELEASE.md` — What version introduced each feature
- `.claude/refs/architecture.md` — System-wide design patterns

---

**Note:** This file is auto-generated. Do not edit it manually. Run `python3 scripts/generate-feature-navigation.py` to update.
"""

    # Write output file
    with open(OUTPUT_FILE, 'w') as f:
        f.write(content)

    # Print summary
    print("")
    print("✅ FEATURE-NAVIGATION.md generated successfully!")
    print("")
    print("📊 Summary:")
    print(f"   Shipped:      {len(shipped)} features")
    print(f"   In-Progress:  {len(in_progress)} features")
    print(f"   Proposed:     {len(proposed)} features")
    print(f"   Total:        {len(shipped) + len(in_progress) + len(proposed)} features")
    print("")
    print(f"📝 Output: {OUTPUT_FILE}")
    print(f"🔄 Last generated: {CURRENT_DATE}")


if __name__ == "__main__":
    main()
