#!/bin/bash
# Auto-generate FEATURE-NAVIGATION.md from actual folder structure
# Run this after adding/removing features to keep navigation up-to-date

set -euo pipefail

DOCS_DIR="/Users/brenn/dev/gasoline"
FEATURES_DIR="${DOCS_DIR}/docs/features/feature"
OUTPUT_FILE="${DOCS_DIR}/docs/features/FEATURE-NAVIGATION.md"

# Extract current date
CURRENT_DATE=$(date +%Y-%m-%d)

echo "🔄 Generating FEATURE-NAVIGATION.md from folder structure..."
echo "📁 Source: $FEATURES_DIR"
echo "📝 Output: $OUTPUT_FILE"

# Create temporary file for navigation
TEMP_FILE=$(mktemp)

# Start building the navigation doc
cat > "$TEMP_FILE" << 'EOF'
---
status: active
scope: feature/navigation
ai-priority: high
tags: [features, navigation, index, lookup, auto-generated]
relates-to: [FEATURE-INDEX.md, README.md]
canonical: true
auto-generated: true
generation-script: scripts/generate-feature-navigation.sh
last-verified: AUTO_GENERATED_DATE
---

# Feature Navigation Index

**For LLM Agents:** Quick lookup to find feature documentation folders and their key files.

**Generated:** AUTO_GENERATED_DATE | **Auto-generated by:** `scripts/generate-feature-navigation.sh`

---

## Quick Lookup: Find a Feature's Docs

### Format

Each entry shows:
- **Feature name** — Unique identifier for the feature
- **Folder path** — Where docs live (`docs/features/feature/<name>/`)
- **Status** — shipped | in-progress | proposed | deprecated
- **Key files** — What's available in this folder

EOF

# Function to detect status from folder content
detect_status() {
  local feature_dir="$1"

  # Check PRODUCT_SPEC for status
  if [ -f "$feature_dir/PRODUCT_SPEC.md" ]; then
    if head -20 "$feature_dir/PRODUCT_SPEC.md" | grep -q "^status: shipped"; then
      echo "shipped"
    elif head -20 "$feature_dir/PRODUCT_SPEC.md" | grep -q "^status: in-progress"; then
      echo "in-progress"
    else
      echo "proposed"
    fi
  elif [ -f "$feature_dir/TECH_SPEC.md" ]; then
    if head -20 "$feature_dir/TECH_SPEC.md" | grep -q "^status: shipped"; then
      echo "shipped"
    elif head -20 "$feature_dir/TECH_SPEC.md" | grep -q "^status: in-progress"; then
      echo "in-progress"
    else
      echo "proposed"
    fi
  else
    echo "proposed"
  fi
}

# Function to get feature purpose/description
get_feature_purpose() {
  local feature_dir="$1"

  if [ -f "$feature_dir/PRODUCT_SPEC.md" ]; then
    grep -m1 "^# " "$feature_dir/PRODUCT_SPEC.md" 2>/dev/null | sed 's/^# //' | head -c 60
  elif [ -f "$feature_dir/FEATURE_PROPOSAL.md" ]; then
    grep -m1 "^# " "$feature_dir/FEATURE_PROPOSAL.md" 2>/dev/null | sed 's/^# //' | head -c 60
  else
    echo "(See folder for details)"
  fi
}

# Function to list files in feature folder
list_feature_files() {
  local feature_dir="$1"

  # Get all markdown files, comma-separated
  find "$feature_dir" -maxdepth 1 -name "*.md" -type f ! -name ".*" | sort | awk -F/ '{print $NF}' | tr '\n' ',' | sed 's/,$//'
}

# Build feature tables by status
{
echo ""
echo "### Shipped Features (Production)"
echo ""
echo "| Feature | Folder | Files | Purpose |"
echo "|---------|--------|-------|---------|"
} >> "$TEMP_FILE"

shipped_count=0
for feature_dir in $(find "$FEATURES_DIR" -maxdepth 1 -type d -name '[a-z]*' | sort); do
  feature_name=$(basename "$feature_dir")
  status=$(detect_status "$feature_dir")

  if [ "$status" = "shipped" ]; then
    files=$(list_feature_files "$feature_dir")
    purpose=$(get_feature_purpose "$feature_dir")

    echo "| $feature_name | \`feature/$feature_name/\` | $files | $purpose |" >> "$TEMP_FILE"
    ((shipped_count++))
  fi
done

{
echo ""
echo "### In-Progress Features"
echo ""
echo "| Feature | Folder | Files | Purpose |"
echo "|---------|--------|-------|---------|"
} >> "$TEMP_FILE"

progress_count=0
for feature_dir in $(find "$FEATURES_DIR" -maxdepth 1 -type d -name '[a-z]*' | sort); do
  feature_name=$(basename "$feature_dir")
  status=$(detect_status "$feature_dir")

  if [ "$status" = "in-progress" ]; then
    files=$(list_feature_files "$feature_dir")
    purpose=$(get_feature_purpose "$feature_dir")

    echo "| $feature_name | \`feature/$feature_name/\` | $files | $purpose |" >> "$TEMP_FILE"
    ((progress_count++))
  fi
done

{
echo ""
echo "### Proposed Features"
echo ""
echo "| Feature | Folder | Files | Purpose |"
echo "|---------|--------|-------|---------|"
} >> "$TEMP_FILE"

proposed_count=0
for feature_dir in $(find "$FEATURES_DIR" -maxdepth 1 -type d -name '[a-z]*' | sort); do
  feature_name=$(basename "$feature_dir")
  status=$(detect_status "$feature_dir")

  if [ "$status" = "proposed" ]; then
    files=$(list_feature_files "$feature_dir")
    purpose=$(get_feature_purpose "$feature_dir")

    echo "| $feature_name | \`feature/$feature_name/\` | $files | $purpose |" >> "$TEMP_FILE"
    ((proposed_count++))
  fi
done

# Add footer sections
cat >> "$TEMP_FILE" << 'EOF'

---

## Navigation by Use Case

### I need to understand what a feature does
→ Read the feature folder's **PRODUCT_SPEC.md**

### I need to implement a feature
→ Read in order: PRODUCT_SPEC.md → TECH_SPEC.md → QA_PLAN.md

### I need to test a feature
→ Read **QA_PLAN.md** for test scenarios, then check if feature-review.md exists for known issues

### I need to find the codebase implementation
→ Read TECH_SPEC.md and look for "**Code References**" section or `filename:line_number` format

### I need to understand design decisions
→ Read the feature-review.md or check `docs/adrs/ADR-<feature-name>.md`

---

## Folder Structure Template

Each feature folder should contain:

```
feature/<feature-name>/
├── PRODUCT_SPEC.md         # Requirements & user stories
├── TECH_SPEC.md            # Implementation details
├── QA_PLAN.md              # Test scenarios & acceptance criteria
├── <feature>-review.md     # Optional: Principal engineer review
└── [Optional files]
    ├── ADR-<feature>.md    # Links here (actually in /docs/adrs/)
    ├── IMPLEMENTATION_PLAN.md
    ├── MIGRATION.md
    └── [Other docs]
```

---

## How to Add a New Feature

1. Create folder: `docs/features/feature/<feature-name>/`
2. Add PRODUCT_SPEC.md (copy template from `docs/templates/FEATURE-TEMPLATE.md`)
3. Add TECH_SPEC.md
4. Add QA_PLAN.md
5. Create ADR at `docs/adrs/ADR-<feature-name>.md`
6. Update **FEATURE-INDEX.md** with new entry
7. Verify YAML frontmatter on all files
8. Get spec review before implementation
9. **Run this script:** `bash scripts/generate-feature-navigation.sh`

---

## Regenerating This Index

To update this navigation after adding/removing features:

```bash
bash scripts/generate-feature-navigation.sh
```

This script automatically:
- Scans `/docs/features/feature/` for all folders
- Detects feature status from PRODUCT_SPEC.md or TECH_SPEC.md
- Extracts file lists from each folder
- Groups features by status
- Generates consistent documentation

---

## Related Documents

- **FEATURE-INDEX.md** — Status table of all features
- **README.md** — Comprehensive features guide for LLMs
- `docs/core/RELEASE.md` — What version introduced each feature
- `.claude/refs/architecture.md` — System-wide design patterns

---

**Note:** This file is auto-generated. Do not edit it manually. Run `scripts/generate-feature-navigation.sh` to update.
EOF

# Replace date placeholder
sed -i '' "s/AUTO_GENERATED_DATE/$CURRENT_DATE/g" "$TEMP_FILE"

# Move temp file to output
mv "$TEMP_FILE" "$OUTPUT_FILE"

# Count total features
total_features=$((shipped_count + progress_count + proposed_count))

echo ""
echo "✅ FEATURE-NAVIGATION.md generated successfully!"
echo ""
echo "📊 Summary:"
echo "   Shipped:      $shipped_count features"
echo "   In-Progress:  $progress_count features"
echo "   Proposed:     $proposed_count features"
echo "   Total:        $total_features features"
echo ""
echo "📝 Output: $OUTPUT_FILE"
echo "🔄 Last generated: $CURRENT_DATE"
