#!/usr/bin/env python3
# pylint: disable=invalid-name
"""
Auto-generate FEATURE-NAVIGATION.md from actual folder structure.
Run this after adding/removing features to keep navigation up-to-date.
"""

from pathlib import Path
from datetime import datetime

DOCS_DIR = Path("/Users/brenn/dev/gasoline")
FEATURES_DIR = DOCS_DIR / "docs/features/feature"
OUTPUT_FILE = DOCS_DIR / "docs/features/FEATURE-NAVIGATION.md"
CURRENT_DATE = datetime.now().strftime("%Y-%m-%d")


def detect_status(feature_dir):
    """Detect feature status from PRODUCT_SPEC.md or TECH_SPEC.md"""
    for spec_file in ["PRODUCT_SPEC.md", "TECH_SPEC.md"]:
        spec_path = feature_dir / spec_file
        if spec_path.exists():
            try:
                with open(spec_path, 'r', encoding='utf-8') as f:
                    content = f.read(500)
                    if "status: shipped" in content:
                        return "shipped"
                    if "status: in-progress" in content:
                        return "in-progress"
            except (OSError, UnicodeDecodeError):
                pass
    return "proposed"


def get_feature_purpose(feature_dir):
    """Extract feature purpose from PRODUCT_SPEC.md or FEATURE_PROPOSAL.md"""
    for spec_file in ["PRODUCT_SPEC.md", "FEATURE_PROPOSAL.md"]:
        spec_path = feature_dir / spec_file
        if spec_path.exists():
            try:
                with open(spec_path, 'r', encoding='utf-8') as f:
                    for line in f:
                        if line.startswith("# "):
                            return line.replace("# ", "").strip()[:60]
            except (OSError, UnicodeDecodeError):
                pass
    return "(See folder for details)"


def list_feature_files(feature_dir):
    """List all markdown files in feature folder"""
    files = []
    for f in sorted(feature_dir.glob("*.md")):
        if not f.name.startswith("."):
            files.append(f.name)
    return ", ".join(files) if files else ""


def scan_features():
    """Scan feature directories and group by status.

    Returns:
        dict: {shipped: [...], in-progress: [...], proposed: [...]}
    """
    groups = {"shipped": [], "in-progress": [], "proposed": []}

    for feature_dir in sorted(FEATURES_DIR.glob("*")):
        if not feature_dir.is_dir() or feature_dir.name.startswith("."):
            continue

        status = detect_status(feature_dir)
        entry = {
            'name': feature_dir.name,
            'files': list_feature_files(feature_dir),
            'purpose': get_feature_purpose(feature_dir),
        }
        groups[status].append(entry)

    return groups


def _build_table_rows(entries):
    """Build markdown table rows from feature entries."""
    return "".join(
        f"| {e['name']} | `feature/{e['name']}/` | {e['files']} | {e['purpose']} |\n"
        for e in entries
    )


def build_navigation_content(groups):
    """Build the full navigation markdown document."""
    header = f"""---
status: active
scope: feature/navigation
ai-priority: high
tags: [features, navigation, index, lookup, auto-generated]
relates-to: [FEATURE-INDEX.md, README.md]
canonical: true
auto-generated: true
generation-script: scripts/generate-feature-navigation.py
last-verified: {CURRENT_DATE}
---

# Feature Navigation Index

**For LLM Agents:** Quick lookup to find feature documentation folders and their key files.

**Generated:** {CURRENT_DATE} | **Auto-generated by:** `scripts/generate-feature-navigation.py`

---

## Quick Lookup: Find a Feature's Docs

### Format

Each entry shows:
- **Feature name** — Unique identifier for the feature
- **Folder path** — Where docs live (`docs/features/feature/<name>/`)
- **Status** — shipped | in-progress | proposed | deprecated
- **Key files** — What's available in this folder

"""

    table_header = "| Feature | Folder | Files | Purpose |\n|---------|--------|-------|---------|"

    sections = [
        ("### Shipped Features (Production)", groups["shipped"]),
        ("### In-Progress Features", groups["in-progress"]),
        ("### Proposed Features", groups["proposed"]),
    ]

    content = header
    for title, entries in sections:
        content += f"{title}\n\n{table_header}\n{_build_table_rows(entries)}\n"

    content += NAVIGATION_FOOTER
    return content


NAVIGATION_FOOTER = """
---

## Navigation by Use Case

### I need to understand what a feature does
\u2192 Read the feature folder's **PRODUCT_SPEC.md**

### I need to implement a feature
\u2192 Read in order: PRODUCT_SPEC.md \u2192 TECH_SPEC.md \u2192 QA_PLAN.md

### I need to test a feature
\u2192 Read **QA_PLAN.md** for test scenarios, then check if feature-review.md exists for known issues

### I need to find the codebase implementation
\u2192 Read TECH_SPEC.md and look for "**Code References**" section or `filename:line_number` format

### I need to understand design decisions
\u2192 Read the feature-review.md or check `docs/adrs/ADR-<feature-name>.md`

---

## Folder Structure Template

Each feature folder should contain:

```
feature/<feature-name>/
\u251c\u2500\u2500 PRODUCT_SPEC.md         # Requirements & user stories
\u251c\u2500\u2500 TECH_SPEC.md            # Implementation details
\u251c\u2500\u2500 QA_PLAN.md              # Test scenarios & acceptance criteria
\u251c\u2500\u2500 <feature>-review.md     # Optional: Principal engineer review
\u2514\u2500\u2500 [Optional files]
    \u251c\u2500\u2500 ADR-<feature>.md    # Links here (actually in /docs/adrs/)
    \u251c\u2500\u2500 IMPLEMENTATION_PLAN.md
    \u251c\u2500\u2500 MIGRATION.md
    \u2514\u2500\u2500 [Other docs]
```

---

## How to Add a New Feature

1. Create folder: `docs/features/feature/<feature-name>/`
2. Add PRODUCT_SPEC.md (copy template from `docs/templates/FEATURE-TEMPLATE.md`)
3. Add TECH_SPEC.md
4. Add QA_PLAN.md
5. Create ADR at `docs/adrs/ADR-<feature-name>.md`
6. Update **FEATURE-INDEX.md** with new entry
7. Verify YAML frontmatter on all files
8. Get spec review before implementation
9. **Run this script:** `python3 scripts/generate-feature-navigation.py`

---

## Regenerating This Index

To update this navigation after adding/removing features:

```bash
python3 scripts/generate-feature-navigation.py
```

This script automatically:
- Scans `/docs/features/feature/` for all folders
- Detects feature status from PRODUCT_SPEC.md or TECH_SPEC.md
- Extracts file lists from each folder
- Groups features by status
- Generates consistent documentation

---

## Related Documents

- **FEATURE-INDEX.md** \u2014 Status table of all features
- **README.md** \u2014 Comprehensive features guide for LLMs
- `docs/core/RELEASE.md` \u2014 What version introduced each feature
- `.claude/refs/architecture.md` \u2014 System-wide design patterns

---

**Note:** This file is auto-generated. Do not edit it manually. Run `python3 scripts/generate-feature-navigation.py` to update.
"""


def print_summary(groups):
    """Print generation summary to stdout."""
    shipped = len(groups["shipped"])
    in_progress = len(groups["in-progress"])
    proposed = len(groups["proposed"])
    total = shipped + in_progress + proposed

    print("")
    print("FEATURE-NAVIGATION.md generated successfully!")
    print("")
    print("Summary:")
    print(f"   Shipped:      {shipped} features")
    print(f"   In-Progress:  {in_progress} features")
    print(f"   Proposed:     {proposed} features")
    print(f"   Total:        {total} features")
    print("")
    print(f"Output: {OUTPUT_FILE}")
    print(f"Last generated: {CURRENT_DATE}")


def main():
    """Generate FEATURE-NAVIGATION.md from folder structure."""
    print("Generating FEATURE-NAVIGATION.md from folder structure...")
    print(f"Source: {FEATURES_DIR}")
    print(f"Output: {OUTPUT_FILE}")

    groups = scan_features()
    content = build_navigation_content(groups)

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(content)

    print_summary(groups)


if __name__ == "__main__":
    main()
